# Generated by Django 5.2 on 2025-04-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_borrowing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(max_length=510),
        ),
    ]
