services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db && 
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    container_name: library-service

  qcluster:
    build:
      context: .
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py qcluster"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    container_name: q-worker

  db:
    image: postgres:16.8-alpine3.20
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - library_db:$PGDATA
    container_name: postgres-db

  redis:
    image: redis:8.0-rc1-alpine3.21
    ports:
      - "6379:6379"
    env_file:
      - .env
    container_name: redis-db

volumes:
  library_db: